
GET http://localhost:8080/api/

###

POST http://localhost:8080/api/auth/login 
content-type: application/json

{
	"email": "admin@bespoke.com",
	"password": "admin24"
}

###

POST http://bespoke-api.onrender.com/api/auth/login 
content-type: application/json

{
	"email": "yusufdaudu51@gmail.com",
	"password": "yusufdaudu51@gmail.com"
}

###

GET http://localhost:8080/api/admin/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE2NTQxNTg5LCJleHAiOjE3MTY1NTU5ODl9.0w-eKOS3CbDaCqJ-qIF2TGnngR36PSdBbaCUkhrWHjI

###

POST http://localhost:8080/api/user/clients 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzE2NTQxNTg5LCJleHAiOjE3MTY1NTU5ODl9.0w-eKOS3CbDaCqJ-qIF2TGnngR36PSdBbaCUkhrWHjI

{
	"hotelName": "Hotel Dave",
	"location": "London",
	"additionalNotes": "This is a note",
	"name": "Emmanuel",
	"email": "emma45@test.com",
	"password": "#password2345"
}

###

GET http://localhost:8080/api/inspectors/

###

POST http://localhost:8080/api/inspectors 
content-type: application/json

{
	"location": "London UK",
	"language": "English",
	"phoneNumber": "090446344354",
	"name": "Emmanuel 2",
	"email": "emma63@test.com",
	"password": "#password2345"
}

###

GET  http://localhost:8080/api/auth/setup 

###
